# Generated by Django 4.2.1 on 2023-06-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_alter_product_description_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
