# Generated by Django 4.2.1 on 2023-06-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
