# Generated by Django 4.2.5 on 2023-10-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('voluntary_registry', models.CharField(blank=True, max_length=255)),
                ('voluntary_status', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('reduction_removal', models.CharField(blank=True, max_length=255)),
                ('methodology_protocol', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('documents', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('project_site_location', models.CharField(blank=True, max_length=255)),
                ('project_developer', models.CharField(blank=True, max_length=255)),
                ('total_credits_issued', models.IntegerField(blank=True)),
                ('total_credits_retired', models.IntegerField(blank=True)),
                ('total_credits_remaining', models.IntegerField(blank=True)),
                ('ccb_certifications', models.CharField(blank=True, max_length=255)),
                ('project_owner', models.CharField(blank=True, max_length=255)),
                ('offset_project_operator', models.CharField(blank=True, max_length=255)),
                ('authorized_project_designee', models.CharField(blank=True, max_length=255)),
                ('verifier', models.CharField(blank=True, max_length=255)),
                ('registry_arb', models.CharField(blank=True, max_length=255)),
                ('project_listed', models.CharField(blank=True, max_length=255)),
                ('project_registered', models.CharField(blank=True, max_length=255)),
                ('project_type', models.CharField(blank=True, max_length=255)),
                ('registry_documents', models.CharField(blank=True, max_length=255)),
                ('project_website', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
