# Generated by Django 4.2.1 on 2023-11-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_delete_project_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
