# Generated by Django 4.2.1 on 2024-02-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_alter_product_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('ENERGY_EFFICIENCY', 'ENERGY_EFFICIENCY'), ('RENEWABLE_ENERGY', 'RENEWABLE_ENERGY'), ('FOREST_MANAGEMENT', 'FOREST_MANAGEMENT')], max_length=255),
        ),
    ]
