# Generated by Django 4.2.1 on 2024-02-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_alter_product_authorized_project_designee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='authorized_project_designee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
