# Generated by Django 4.2.1 on 2024-02-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_alter_product_authorized_project_designee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('ENERGY_EFFICIENCY', 'ENERGY_EFFICIENCY'), ('RENEWABLE_ENERGY', 'RENEWABLE_ENERGY'), ('FOREST_MANAGEMENT', 'FOREST_MANAGEMENT')], max_length=255, null=True),
        ),
    ]
