# Generated by Django 4.2.1 on 2024-02-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0023_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
