# Generated by Django 4.2.1 on 2024-02-07 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, null=True, max_length=255, unique=True)),
                ('project_name', models.CharField(blank=True, null=True, max_length=255)),
                ('voluntary_registry', models.CharField(blank=True, max_length=255)),
                ('voluntary_status', models.CharField(blank=True, null=True, max_length=255)),
                ('scope', models.CharField(blank=True, null=True, max_length=255)),
                ('reduction_removal', models.CharField(blank=True, null=True, max_length=255)),
                ('methodology_protocol', models.CharField(blank=True, null=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('documents', models.CharField(blank=True, null=True, max_length=255)),
                ('country', models.CharField(blank=True, null=True, max_length=255)),
                ('state', models.CharField(blank=True, null=True, max_length=255)),
                ('project_site_location', models.CharField(blank=True, null=True, max_length=255)),
                ('project_developer', models.CharField(blank=True, null=True, max_length=255)),
                ('total_credits_issued', models.IntegerField(blank=True, default=0)),
                ('total_credits_retired', models.IntegerField(blank=True, default=0)),
                ('total_credits_remaining', models.IntegerField(blank=True, default=0)),
                ('ccb_certifications', models.CharField(blank=True, null=True, max_length=255)),
                ('project_owner', models.CharField(blank=True, null=True, max_length=255)),
                ('offset_project_operator', models.CharField(blank=True, null=True, max_length=255)),
                ('verifier', models.CharField(blank=True, null=True, max_length=255)),
                ('registry_arb', models.CharField(blank=True, max_length=255)),
                ('project_listed', models.CharField(blank=True, null=True, max_length=255)),
                ('project_registered', models.CharField(blank=True, null=True, max_length=255)),
                ('project_type', models.CharField(blank=True, max_length=255)),
                ('registry_documents', models.CharField(blank=True, max_length=255)),
                ('project_website', models.CharField(blank=True, null=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
    ]
